### ISSUE TITLE
Link to vendor assets rather than copy them?

### ISSUE THREAD

**Issue by fuhrmanator** [BlackrockDigital/startbootstrap-clean-blog-jekyll#189]
I am new to Jekyll, but I see this theme has copies of Bootstrap, Jquery, etc. in the assets folder. It would seem to me that the best way to do it would not have copies of these files, but somehow link to them on the web? Perhaps Jekyll is not designed for that? Anyway, if it is, I would like to see how this theme could leverage that. I have to commit over 1500 files to my github copy of my blog, and that doesn't make sense. Perhaps I'm doing something wrong? My interest in using Jekyll is to deploy my blog with GitHub pages.

**Comment by NoobCam** [comment]
Couple of things here,

I don't think static content pages were designed to link to vendor assets. I could be wrong as well. It kinda defeats to nature of a static web page.

To address the issue with committing so many files, do you have a .gitignore file setup? Below is what I have in mine
```
_site/
.sass-cache/
.jekyll-cache/
.jekyll-metadata
```

**Comment by fuhrmanator** [comment]
Thanks for responding. Before posting this issue, I even tried adding vendor to .gitignore per https://github.com/jekyll/jekyll/issues/6920. It solves the many file commit, but there are no bootstrap or jQuery CSS and the site is useless on GitHub pages.

I have coded a static web app that used jQuery and bootstrap and it was a dozen vendor files at most.

**Comment by davidtmiller** [comment]
There are a few files in the `vendor` directory that are needed, like the `vendor/startbootstrap-clean-blog` directory since that contains the JS and the SCSS from the base theme which is a dependency of this Jekyll version.

If you wanted to, you could remove the Bootstrap and jQuery directories and references those dependencies using a CDN instead. You would need to update the `_includes/head.html` file if you did this.
