### ISSUE TITLE
Amount of words is displayed

### ISSUE THREAD

**Issue by dr4gon37** [BlackrockDigital/startbootstrap-clean-blog-jekyll#192]
Hello Everyone!
I have some issue: I don't know how to hide the word counter on my site:
[image](https://ibb.co/4TffdRz)
Link to my blog: [my blog](https://ceblog.pl)
Link to my repository: [repository](https://github.com/dr4gon37/GithubPage)
I searched in Clean Theme _includes and  _layout folder my posts.md  and I found nothing.

**Comment by clintonb** [comment]
The issue is in [_includes/read_time.html](https://github.com/BlackrockDigital/startbootstrap-clean-blog-jekyll/blob/e3ca5e9e4e33510a052c4afe63842d54ef5f6eaa/_includes/read_time.html). If the word count is less than 270 words, the word count is displayed. I solved this by copying the file/path and removing `{{ words }}`.

**Comment by dr4gon37** [comment]
Yea, I see, I don't know why I didn't check it. Thank you so much, I appreciate that you wanted to solve my little stupid problem :)
